### Create Product

POST http://localhost:8080/api/products
X-Api-Key: SECRET
Content-Type: application/json
Accept: application/json

{
  "id": "A0010",
  "name": "Mac Book Pro 15",
  "price": "30000000",
  "quantity": "10"
}

### Create Product Invalid

POST http://localhost:8080/api/products
X-Api-Key: SECRET
Content-Type: application/json
Accept: application/json

{
  "id": "",
  "name": "",
  "price": "0",
  "quantity": "-10"
}

### Get Product

GET http://localhost:8080/api/products/A0001
X-Api-Key: SECRET
Accept: application/json

### Get Product Not Found

GET http://localhost:8080/api/products/SALAH
X-Api-Key: SECRET
Accept: application/json

### Update Product

PUT http://localhost:8080/api/products/A0001
X-Api-Key: SECRET
Content-Type: application/json
Accept: application/json

{
  "name": "Mac Book Pro 15 2020",
  "price": "40000000",
  "quantity": "100"
}

### Update Product Not Found

PUT http://localhost:8080/api/products/SALAH
X-Api-Key: SECRET
Content-Type: application/json
Accept: application/json

{
  "name": "Mac Book Pro 15 2020",
  "price": "40000000",
  "quantity": "100"
}

### Update Product With Invalid Body

PUT http://localhost:8080/api/products/A0001
X-Api-Key: SECRET
Content-Type: application/json
Accept: application/json

{
  "name": "",
  "price": "0",
  "quantity": "-10"
}

### Delete Product

DELETE http://localhost:8080/api/products/A0001
X-Api-Key: SECRET
Accept: application/json

### List Product

GET http://localhost:8080/api/products
X-Api-Key: SECRET
Accept: application/json

### List Product with size parameter

GET http://localhost:8080/api/products?size=5
X-Api-Key: SECRET
Accept: application/json

### List Product with size and parameter

GET http://localhost:8080/api/products?size=5&page=1
X-Api-Key: SECRET
Accept: application/json

GET 'https://smarttrade.texcoms.com/Texcoms/api/offersummarySimilarMachines',
contentType: "application/json",
dataType: 'json',
crossDomain: true,
data: JSON.stringify({
			'authTicket': smartTradeKey,
			'offerId': offerId, 
			'pageStart': pageStart,
			'pageSize': recordsPerPage
		}),


GET https://smarttrade.texcoms.com/Texcoms/api/offersummaryview/10755
type: 'GET',
contentType: 'application/json',
dataType: 'json',
crossDomain: true